name: Plugin CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    name: Test
    runs-on: ubuntu-latest
    environment: credentials

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v21
        with:
          repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/azalealibrary/azaleacore" }]'
          servers: '[{ "id": "github", "username": "azlaelibrary", "password": "${env.DEPLOY_TOKEN}" }]'

      - name: build
        uses: gradle/gradle-build-action@v2

      - name: test
        run:  mvn -ntp clean test
